import express from 'express'
import fetch from 'node-fetch'
import cors from 'cors'
import * as dotenv from 'dotenv'
import * as path from 'path'
import { mcpay, getStats } from 'mcpay'

// ==========================================
// LOAD ENV FROM ROOT
// ==========================================
dotenv.config({ path: path.join(__dirname, '../../../.env') })

import { getWalletBalance, getRecentTransactions, getWalletPnL } from './zerion'
import { initXMTP, sendPaymentAlert } from './xmtp-notifier'

const app = express()

// ==========================================
// ENABLE CORS FOR THE DASHBOARD
// ==========================================
app.use(cors())
app.use(express.json())

// Landing Page for the Tool Server
app.get('/', (req, res) => {
  res.send(`
    <div style="background: #0a0a0a; color: #00ff88; font-family: monospace; padding: 40px; min-height: 100vh; text-align: center;">
      <h1 style="font-size: 48px;">⚡ MCPay Engine</h1>
      <p style="color: #666; font-size: 20px;">The autonomous machine economy is live.</p>
      <div style="border: 1px solid #00ff8833; padding: 20px; border-radius: 12px; display: inline-block; margin-top: 40px; text-align: left; background: #111;">
        <h3 style="color: #fff; margin-top: 0;">🔧 Native Tool Endpoints:</h3>
        <ul style="color: #888;">
          <li>POST /tools/weather-data — $0.01</li>
          <li>POST /tools/url-summarizer — $0.02</li>
          <li>POST /tools/check-portfolio — $0.05</li>
          <li>GET  /stats — Real-time earnings</li>
        </ul>
        <p style="color: #00ff88; font-size: 14px;">OWS x402 Security Middleware: ACTIVE</p>
      </div>
      <br/><br/>
      <a href="http://localhost:3000" style="color: #0088ff; text-decoration: none;">Go to Registry Dashboard &rarr;</a>
    </div>
  `)
})

// ==========================================
// CONFIG WALLETS & IDENTITIES
// ==========================================
const MY_WALLET = process.env.TOOL_WALLET_ADDRESS as `0x${string}`
const AGENT_WALLET = process.env.AGENT_WALLET_ADDRESS || '0xCc9aF4932E78ABdD3640993cb45944cE2775b37b'

// ==========================================
// ZERION ENDPOINTS (Dashboard ke liye)
// ==========================================
app.get('/zerion/wallet-health', async (req, res) => {
  const agentAddr = AGENT_WALLET
  const toolAddr = MY_WALLET
  
  try {
    const [agentBalance, toolBalance, agentTxs, agentPnl] = await Promise.all([
      getWalletBalance(agentAddr),
      getWalletBalance(toolAddr),
      getRecentTransactions(agentAddr, 5),
      getWalletPnL(agentAddr)
    ])
    
    res.json({
      agent: { ...agentBalance, ...agentPnl },
      tool: toolBalance,
      recentTxs: agentTxs,
      timestamp: new Date().toISOString()
    })
  } catch (e) {
    res.status(500).json({ error: 'Failed to fetch wallet health from Zerion' })
  }
})

// ==========================================
// TOOL 1: WEATHER DATA ($0.01 per call)
// ==========================================
app.use(...mcpay({
  price: '$0.01',
  walletAddress: MY_WALLET,
  toolName: 'weather-data',
  description: 'Real-time weather for any city',
  onPayment: async (stats) => {
    await sendPaymentAlert({
      toAddress: AGENT_WALLET,
      toolName: 'weather-data',
      amount: '$0.01',
      totalEarned: stats.totalEarned,
      callNumber: stats.totalCalls
    })
  }
}))

app.post('/tools/weather-data', async (req, res) => {
  const { city } = req.body
  try {
    const response = await fetch(`https://wttr.in/${city}?format=j1`)
    const data: any = await response.json()
    
    res.json({
      city,
      temperature: data.current_condition[0].temp_C,
      feels_like: data.current_condition[0].FeelsLikeC,
      description: data.current_condition[0].weatherDesc[0].value,
      humidity: data.current_condition[0].humidity
    })
  } catch (e) {
    res.status(500).json({ error: "Failed to fetch weather data" })
  }
})

// ==========================================
// TOOL 2: URL SUMMARIZER ($0.02 per call)
// ==========================================
app.use(...mcpay({
  price: '$0.02',
  walletAddress: MY_WALLET,
  toolName: 'url-summarizer',
  description: 'Summarize any webpage',
  onPayment: async (stats) => {
    await sendPaymentAlert({
      toAddress: AGENT_WALLET,
      toolName: 'url-summarizer',
      amount: '$0.02',
      totalEarned: stats.totalEarned,
      callNumber: stats.totalCalls
    })
  }
}))

app.post('/tools/url-summarizer', async (req, res) => {
  const { url } = req.body
  res.json({
    url,
    summary: "This is a summary generated by the URL summarizer tool. The content was processed and compressed into these key points.",
    wordCount: 1250
  })
})

// ==========================================
// TOOL 3: ZERION PORTFOLIO CHECK ($0.05 per call)
// ==========================================
app.use(...mcpay({
  price: '$0.05',
  walletAddress: MY_WALLET,
  toolName: 'check-portfolio',
  description: 'Check crypto portfolio value via Zerion API',
  onPayment: async (stats) => {
    await sendPaymentAlert({
      toAddress: AGENT_WALLET,
      toolName: 'check-portfolio',
      amount: '$0.05',
      totalEarned: stats.totalEarned,
      callNumber: stats.totalCalls
    })
  }
}))

app.post('/tools/check-portfolio', async (req, res) => {
  const { address } = req.body
  console.log(`[Zerion] Checking portfolio for ${address}`)
  try {
    const apiKey = process.env.ZERION_API_KEY
    if (!apiKey) throw new Error("ZERION_API_KEY missing")

    const authHeader = `Basic ${Buffer.from(apiKey + ':').toString('base64')}`
    const url = `https://api.zerion.io/v1/wallets/${address}/portfolio?currency=usd`
    
    const response = await fetch(url, {
      headers: {
        'Authorization': authHeader,
        'accept': 'application/json'
      }
    })
    
    const data: any = await response.json()
    res.json(data)
  } catch (e: any) {
    res.status(500).json({ error: e.message })
  }
})

// ==========================================
// STATS ENDPOINT (Registry ke liye)
// ==========================================
app.get('/stats', (req, res) => {
  res.json(getStats())
})

// ==========================================
// MCP MANIFEST
// ==========================================
app.get('/.well-known/mcp', (req, res) => {
  res.json({
    name: 'MCPay Demo Server',
    version: '1.0.0',
    tools: [
      {
        name: 'weather-data',
        endpoint: '/tools/weather-data',
        price: '$0.01',
        description: 'Real-time weather for any city'
      },
      {
        name: 'url-summarizer', 
        endpoint: '/tools/url-summarizer',
        price: '$0.02',
        description: 'Summarize any webpage'
      },
      {
        name: 'check-portfolio',
        endpoint: '/tools/check-portfolio',
        price: '$0.05',
        description: 'Check crypto portfolio value via Zerion API'
      }
    ]
  })
})

const PORT = 3001
app.listen(PORT, async () => {
  console.log(`\n\n🔧 MCPay Tool Server (CORS ENABLED) running on port ${PORT}`)
  await initXMTP()
  console.log(`✅ XMTP notifications: ACTIVE`)
  console.log(`✅ Zerion integration: ACTIVE`)
})
